spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.58.84.184:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
#  dubbo:
#    application:
#      name: dubbo-provider #当前应用名称 主要用来给 zokeeper 注册中心计算应用间依赖关系
#    registry:
#      address: zookeeper://10.58.84.184:2181
#    protocol:
#      name: dubbo
#      port: 20880 #该应用用dubbo协议在20880端口暴露服务 其他应用可以通过这个接口调用服务
#    scan: com.example.demo.dubboapi   2.0.0 版本未配置 DubboProperties scan属性

  dubbo:
    application:
      name: dubbot-consumer
    register:
      address: zookeeper://10.58.84.184:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.example.demo.dubboclient

#web服务启动端口配置
server:
  port: 8233


#test start
const-dev: dev 1

connection:
  userName : admin
  password: 1qaz2ws
  remoteAddress: 127.0.0.1,10.58.84.184
  config:
    url: 127.0.0.1
    port: 8080

#test end
