#设置application.properties 如使用开发环境用一下代码 spring.profiles.active
spring:
  profiles:
    active:
      @env@
  aop:
    auto: true #开启aop配置

mybatis-plus:
  #MyBatis 配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  #实体扫描 多个package用逗号或者分号分割，注册后在Mapper对应的xml文件中可以直接使用类名，不用全限定的类名
  typeAliasesPackage: com.example.demo.domain

#config-location和configuration不能同时存在
#  configuration:
#    safe-row-bounds-enabled: false
#    map-underscore-to-camel-case: false
#    aggressive-lazy-loading: false
#    multiple-result-sets-enabled: false
#    use-generated-keys: false
#    cache-enabled: false
#    call-setters-on-nulls: false
#    return-instance-for-empty-row: false

  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0  #全局 主键策略 策略配置
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    db-config:
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值
      field-strategy: NOT_EMPTY

#日志级别  与性能分析插件 PerformanceInterceptor同步打印sql语句
#logging.level.* =LEVEL   *为包名或Logger名
logging:
  level:
    root: INFO #root 日志以WARN级别输出
    com.example.demo.dao: trace #com.example.demo.dao 包下所有class以TRACE级别输出
  pattern:
    console: '%p%m%n'


server:
  port: 8233
